language: rust
dist: trusty
rust:
  - stable

git:
  depth: 1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mpv
  - RUST_BACKTRACE=1 cargo build --release
  - RUST_BACKTRACE=1 cargo test
  - RUST_BACKTRACE=1 cargo doc
